# Generated by Django 4.0.4 on 2022-05-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_description_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
